version: 1
formatters:
  console:
    format: '%(asctime)s:%(name)s:%(levelname)s: %(message)s'
    datefmt: '%H:%M:%S'
  file:
    format: '%(asctime)s:%(name)s:%(levelname)s: %(message)s'
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    stream: ext://sys.stdout
  file:
    level: DEBUG
    class: logging.handlers.RotatingFileHandler
    formatter: file
    filename: log_file
    maxBytes: 500000
    backupCount: 5
loggers:
  '':
    level: DEBUG
    handlers: [console, file]
    propagate: no
disable_existing_loggers: False # 既存のロガーを無効化しない
